// LOCAL STORAGE
export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_SINGLE_POST = 'FETCH_SINGLE_POST';
export const FETCH_POST_COMMENTS = 'FETCH_POST_COMMENTS';
export const CLEAR_POST = 'CLEAR_POST';

